name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
